'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Gestion_Hopital.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _0a468e18c5ac5538af971fc9beaf026c() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("0a468e18c5ac5538af971fc9beaf026c", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _309136f35f24d55337f523041b5a976b() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("309136f35f24d55337f523041b5a976b", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _38de84798b46b16808db55498b7796c2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("38de84798b46b16808db55498b7796c2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _52050fb74f24bb0ef61c76a6e89f4548() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("52050fb74f24bb0ef61c76a6e89f4548", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _53223bf7b3558866bf3ef9326290ea21() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("53223bf7b3558866bf3ef9326290ea21", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property _64720da758d7aaa748dd8da4a9b91e96() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("64720da758d7aaa748dd8da4a9b91e96", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property b6a057a29ef49baa98b592b17a9edde5() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("b6a057a29ef49baa98b592b17a9edde5", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Blue_Cross_Circle_Stethoscope_Logo_Stock_Vector___Illustration_of_company__activities__171160300() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Blue Cross Circle Stethoscope Logo Stock Vector - Illustration of company, activi"& _ 
                        "ties_ 171160300", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c001e6ca5a1b7c4670689c25673a83b4() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c001e6ca5a1b7c4670689c25673a83b4", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property c001e6ca5a1b7c4670689c25673a83b41() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("c001e6ca5a1b7c4670689c25673a83b41", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property caab6ce7f4e69d448e2430927e494049() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("caab6ce7f4e69d448e2430927e494049", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Der_Patientenservice__ärztlicher_Notdienst____116117_de() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Der Patientenservice (ärztlicher Notdienst) _ 116117_de", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property f4add2fcd72e98912488403311240c9d() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("f4add2fcd72e98912488403311240c9d", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Medical_Icons___Micro_Animations() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Medical Icons _ Micro-Animations", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Medical_Syringe_Hd_Transparent__Medical_Border_Blue_Syringe_Pills__Medical__Border__Blue_PNG_Image_For_Free_Download() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Medical Syringe Hd Transparent, Medical Border Blue Syringe Pills, Medical, Borde"& _ 
                        "r, Blue PNG Image For Free Download", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property patient_forms_drib_lrg_jpg_by_Josh_Warren__1_() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("patient_forms_drib_lrg_jpg by Josh Warren (1)", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property prendre_rdv_creation_site_web() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("prendre-rdv-creation-site-web", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property 安全用藥_扁平化_醫療促銷_簡約展板背景圖桌布手機桌布圖片免費下載___Pngtree() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("安全用藥 扁平化 醫療促銷 簡約展板背景圖桌布手機桌布圖片免費下載 - Pngtree", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
